# Generated by Django 3.0.7 on 2020-10-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchtime', '0003_meal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='photo',
        ),
    ]
