# Generated by Django 3.0.7 on 2020-10-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchtime', '0005_auto_20201006_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date']},
        ),
    ]
